---

# configuramos kubeadm
- name: configura kubeadm
  command: kubeadm config images pull
  become: yes

# Reseteamos el plugin CNI (Container Network Interface) para poder ejecutarlo reiteradamente
#- name: resetea kubeadm init
#  command: kubeadm reset
#  notify: "instala plugin CNI"
#  become: yes

# Instalamos el plugin CNI (Container Network Interface) de kubernetes y definimos la red de los PODs 
- name: instala plugin CNI
  command: kubeadm init --pod-network-cidr 192.169.0.0/16
  register: kubeadm_init_stdout
  become: yes


# autorizamos al usuario root acceder al cluster
# creamos la ruta
- name: Creamos el directorio para root
  file:
    path: /root/.kube
    state: directory
    mode: '0755'

# autorizamos al usuario root acceder al cluster
# copiamos el fichero
- name: Copiamos ficheros admin 
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: '0755'
  become: yes
  notify: Ejecuta chown

# Obtiene los nodos de k8s 
- name: obtiene los nodos de k8s
  command: kubectl get nodes
  become: yes

