---

# instalamos y configuramos cilium
#- name:  instala Cilium
#  command: kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.9/install/kubernetes/quick-install.yaml 



# Obtiene los nodos de k8s 
- name: obtiene los nodos de k8s
  command: kubectl get nodes
  become: yes

# Obtiene los nodos de k8s 
- name: obtiene los nodos de k8s
  command: kubectl get pods -A
  become: yes
