---

# borramos kubelete, kubeadm y kubectl
- name: borra master
  hosts: workers 
  gather_facts: true
  become: yes
  tasks:
          - name: borra k8s
            yum:
                    name: ['kubectl', 'kubelete', 'kubeadm']
                    state: removed
            become: yes

